version: '3.8'

services:
  taskmanager-app:
    build: .
    container_name: taskmanager-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:mysql://taskmanager-db:3306/taskmanager_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
    depends_on:
      - taskmanager-db

  taskmanager-db:
    image: mysql:8.0
    container_name: taskmanager-db
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taskmanager_db
    volumes:
      - db_data:/var/lib/mysql

  maven_test:
    image: maven:3.9.4-eclipse-temurin-17
    container_name: taskmanager-tests
    working_dir: /app
    volumes:
      - .:/app
    command: mvn test

volumes:
  db_data:
