name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Install Doxygen
        run: sudo apt-get update && sudo apt-get install -y doxygen graphviz
      
      - name: Generate Doxygen documentation
        run: |
          if [ -f "Doxyfile" ]; then
            doxygen Doxyfile
          else
            echo "Doxyfile not found, skipping Doxygen documentation"
          fi
        continue-on-error: true

      - name: Generate Maven Site
        run: mvn site

      - name: Generate JaCoCo Report
        run: mvn jacoco:report

      - name: Prepare documentation for GitHub Pages
        run: |
          # Crear directorio principal para la documentación
          mkdir -p gh-pages
          
          # Crear estructura de directorios
          mkdir -p gh-pages/docs
          mkdir -p gh-pages/site
          mkdir -p gh-pages/jacoco
          
          # Copiar documentación generada por Doxygen
          if [ -d "docs/html" ]; then
            cp -r docs/html/* gh-pages/docs/
          elif [ -d "target/doxygen" ]; then
            mkdir -p gh-pages/doxygen
            cp -r target/doxygen/* gh-pages/doxygen/
          fi
          
          # Copiar Maven Site
          cp -r target/site/* gh-pages/site/
          
          # Copiar informes JaCoCo
          cp -r target/site/jacoco/* gh-pages/jacoco/ || echo "No JaCoCo reports found"
          
          # Crear un archivo index.html 
          cat > gh-pages/index.html << 'EOL'
          <!DOCTYPE html>
          <html>
          <head>
            <title>Project Documentation</title>
            <style>
              body { font-family: Arial, sans-serif; margin: 0; padding: 20px; line-height: 1.6; }
              .container { max-width: 800px; margin: 0 auto; }
              h1 { color: #2c3e50; }
              .navigation { background-color: #f8f9fa; padding: 15px; border-radius: 4px; margin-bottom: 20px; }
              .navigation a { margin-right: 15px; text-decoration: none; color: #3498db; }
              .navigation a:hover { text-decoration: underline; }
            </style>
          </head>
          <body>
            <div class="container">
              <h1>Project Documentation</h1>
              <div class="navigation">
                <a href="./site/">Maven Site</a>
                <a href="./docs/">API Documentation</a>
                <a href="./jacoco/">Code Coverage</a>
              </div>
              <p>Welcome to the project documentation page. Please use the links above to navigate through different sections.</p>
            </div>
          </body>
          </html>
          EOL
          
          # Deshabilitar Jekyll
          touch gh-pages/.nojekyll

      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'gh-pages'
        
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
